.base: &base
  image: nvidia/cuda:12.2.0-devel-ubuntu22.04
  before_script:
    - ls -la /dev/nvidia* || echo "No GPU devices"
    - apt-get update -qq && apt-get install -y -qq cmake git clang-format

00-hello-world:
  <<: *base
  rules:
    - if: $CI_COMMIT_BRANCH == "submits/00-hello-world"
  script:
    - mkdir build && cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --target -j16 test_hello_world
    - CUDA_VISIBLE_DEVICES=1,2,3,4,5,6 ./test_hello_world

01-fibonacci:
  <<: *base
  rules:
    - if: $CI_COMMIT_BRANCH == "submits/01-fibonacci"
  script:
    - mkdir build && cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --target -j16 test_fibonacci
    - CUDA_VISIBLE_DEVICES=1,2,3,4,5,6 ./test_fibonacci

02-binary-image:
  <<: *base
  rules:
    - if: $CI_COMMIT_BRANCH == "submits/02-binary-image"
  script:
    - mkdir build && cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --target -j16 test_binary_image
    - CUDA_VISIBLE_DEVICES=1,2,3,4,5,6 ./test_binary_image
    - cmake --build . --target -j16 benchmark_binary_image
    - CUDA_VISIBLE_DEVICES=1,2,3,4,5,6 ./benchmark_binary_image

03-tree:
  <<: *base
  rules:
    - if: $CI_COMMIT_BRANCH == "submits/03-tree"
  script:
    - mkdir build && cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --target -j16 test_tree
    - CUDA_VISIBLE_DEVICES=1,2,3,4,5,6 ./test_tree
    - cmake --build . --target -j16 benchmark_tree
    - CUDA_VISIBLE_DEVICES=1,2,3,4,5,6 ./benchmark_tree

04-vector:
  <<: *base
  rules:
    - if: $CI_COMMIT_BRANCH == "submits/04-vector"
  script:
    - mkdir build && cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --target -j16 test_vector
    - CUDA_VISIBLE_DEVICES=1,2,3,4,5,6 ./test_vector
    - cmake --build . --target -j16 benchmark_vector
    - CUDA_VISIBLE_DEVICES=1,2,3,4,5,6 ./benchmark_vector

05-transpose:
  <<: *base
  rules:
    - if: $CI_COMMIT_BRANCH == "submits/05-transpose"
  script:
    - mkdir build && cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --target -j16 test_transpose
    - CUDA_VISIBLE_DEVICES=1,2,3,4,5,6 ./test_transpose
    - cmake --build . --target -j16 benchmark_transpose
    - CUDA_VISIBLE_DEVICES=1,2,3,4,5,6 ./benchmark_transpose

06-gemm-v0:
  <<: *base
  rules:
    - if: $CI_COMMIT_BRANCH == "submits/06-gemm-v0"
  script:
    - mkdir build && cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --target -j16 test_gemm_v0
    - CUDA_VISIBLE_DEVICES=1,2,3,4,5,6 ./test_gemm_v0
    - cmake --build . --target -j16 benchmark_gemm_v0
    - CUDA_VISIBLE_DEVICES=1,2,3,4,5,6 ./benchmark_gemm_v0

07-prefsums:
  <<: *base
  rules:
    - if: $CI_COMMIT_BRANCH == "submits/07-prefsums"
  script:
    - mkdir build && cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --target -j16 test_prefsums
    - CUDA_VISIBLE_DEVICES=1,2,3,4,5,6 ./test_prefsums
    - cmake --build . --target -j16 benchmark_prefsums
    - CUDA_VISIBLE_DEVICES=1,2,3,4,5,6 ./benchmark_prefsums
