# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\x10trt.inference.v1\"@\n\x0cInferRequest\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x11\n\trgb_image\x18\x03 \x01(\x0c\"5\n\x0f\x43lassPrediction\x12\x13\n\x0b\x63lass_index\x18\x01 \x01(\x05\x12\r\n\x05score\x18\x02 \x01(\x02\"@\n\rInferResponse\x12/\n\x04top5\x18\x01 \x03(\x0b\x32!.trt.inference.v1.ClassPrediction2_\n\x10InferenceService\x12K\n\x08\x43lassify\x12\x1e.trt.inference.v1.InferRequest\x1a\x1f.trt.inference.v1.InferResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFERREQUEST']._serialized_start=37
  _globals['_INFERREQUEST']._serialized_end=101
  _globals['_CLASSPREDICTION']._serialized_start=103
  _globals['_CLASSPREDICTION']._serialized_end=156
  _globals['_INFERRESPONSE']._serialized_start=158
  _globals['_INFERRESPONSE']._serialized_end=222
  _globals['_INFERENCESERVICE']._serialized_start=224
  _globals['_INFERENCESERVICE']._serialized_end=319
# @@protoc_insertion_point(module_scope)
